spring:
  datasource:
    url: jdbc:mysql://192.168.33.21:3306/course?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  http:
    encoding:
      force-response: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/**/*.xml
#  type-aliases-package: com.lagou.pojo